### ISSUE TITLE
Getting Started guide

### ISSUE THREAD

**Issue by headwinds** [Foppygames/sword-of-the-orc-king#1]
I'm new to Lua and discovered your awesome game!

Without knowing much about Love, I thought I could first try your game in the Playdate simulator. No dice. 

It seems like [Playdate](https://play.date/dev/) & [Love](https://love2d.org/) are both similar yet different enough that they are not compatible out of the box.

Specifically, I can see that Playdate uses an `import` syntax and love has `require`

I'm sure you an expert in Lua by now so I wanted to contribute a guide for someone who has had little to no experience. 

These are the steps I would take for Mac User (apologies I can only do Mac and hopefully someone will offer the PC side)

1.. Download the Love [64-bit zipped](https://github.com/love2d/love/releases/download/11.4/love-11.4-macos.zip) and unzip it in your downloads folder and drag the file into your application folder

If you happen to double-click and run the love file like I did, you might be surprised to see this balloon thing in a window. Don't Panic. This is normal so close the window and let's continue. 
<img width="798" alt="Screenshot 2023-08-14 at 10 31 56 PM" src="https://github.com/Foppygames/sword-of-the-orc-king/assets/68402/cf908f1b-f35e-424c-b07c-5e27c1caaf83">

2. Git clone this repo [sword-of-the-orc-king](https://github.com/Foppygames/sword-of-the-orc-king)
3. After you've cloned this repo, cd in the  sword-of-the-orc-king directory and run:
```
open -n -a love .
```
If all goes well, you should see this screen... 

<img width="1274" alt="Screenshot 2023-08-14 at 10 34 25 PM" src="https://github.com/Foppygames/sword-of-the-orc-king/assets/68402/2ca8e71e-d2ba-4c67-aa16-5ce73f43eb73">

Since love is in your application folder, it can run the main.lua source code.

**Comment by Foppygames** [comment]
Hello and thanks for your nice words about my game. This kind of guide would certainly be helpful at some stage, but currently my game is hardly playable. I sort of put this project on hold, so it is meant as a code example.  But I will certainly keep this in mind.

**Comment by headwinds** [comment]
thanks @Foppygames - I'm going to close this issue and start a dev.to article instead to promote your repo as the work-n-progress it is - there is a lot of value in how you structured your project and rendered the dungeon! 

I would be keen to see how you manage some of performance issues during combat in the future otherwise I did actually have fun playing it while wandering the tunnels and using my imagination - the beauty of  classic rogue-likes 🗝️
